/**
 * NEU-PERSIAN FAMILY TREE BUILDER - Complete Application
 */

// 1. JALALI DATE ENGINE
class JalaliEngine {
    gregorianToJalali(gy, gm, gd) {
        const g_d_m = [0,31,59,90,120,151,181,212,243,273,304,334];
        let jy = (gy<=1600)?0:979; gy-=(gy<=1600)?621:1600;
        let gy2=(gm>2)?(gy+1):gy;
        let days=(365*gy)+Math.floor((gy2+3)/4)-Math.floor((gy2+99)/100)+Math.floor((gy2+399)/400)-80+gd+g_d_m[gm-1];
        jy+=33*Math.floor(days/12053); days%=12053; jy+=4*Math.floor(days/1461); days%=1461;
        if(days>365){jy+=Math.floor((days-1)/365);days=(days-1)%365;}
        let jm=(days<186)?1+Math.floor(days/31):7+Math.floor((days-186)/30);
        let jd=1+((days<186)?(days%31):((days-186)%30));
        return {year:jy,month:jm,day:jd};
    }
    jalaliToGregorian(jy,jm,jd){
        let gy=(jy<=979)?621:1600; jy-=(jy<=979)?0:979;
        let days=(365*jy)+(Math.floor(jy/33)*8)+Math.floor(((jy%33)+3)/4)+78+jd+((jm<7)?(jm-1)*31:((jm-7)*30)+186);
        gy+=400*Math.floor(days/146097); days%=146097;
        if(days>36524){gy+=100*Math.floor(--days/36524);days%=36524;if(days>=365)days++;}
        gy+=4*Math.floor(days/1461); days%=1461;
        if(days>365){gy+=Math.floor((days-1)/365);days=(days-1)%365;}
        let gd=days+1;
        const sal_a=[0,31,((gy%4===0&&gy%100!==0)||(gy%400===0))?29:28,31,30,31,30,31,31,30,31,30,31];
        let gm; for(gm=0;gm<13&&gd>sal_a[gm];gm++)gd-=sal_a[gm];
        return {year:gy,month:gm,day:gd};
    }
    parseDate(s){if(!s)return null;const p=s.split('/').map(x=>parseInt(x.trim()));return(p.length===3&&!p.some(isNaN))?p:null;}
    formatDate(y,m,d){const n=x=>x.toString().padStart(2,'0');return `${y}/${n(m)}/${n(d)}`;}
}

// 2. I18N MANAGER
class I18nManager{
    constructor(){this.currentLang='fa';this.translations={fa:{appTitle:'شجره‌نامه',newTree:'شجره جدید',openFolder:'پوشه',saveNow:'ذخیره',addPerson:'افزودن فرد',autoArrange:'مرتب‌سازی',calcRelation:'نسبت‌سنجی',export:'خروجی',searchPlaceholder:'جستجو...',ready:'آماده',nodes:'فرد',relationships:'رابطه',editPerson:'ویرایش',uploadPhoto:'بارگذاری عکس',removePhoto:'حذف عکس',firstName:'نام',lastName:'نام خانوادگی',gender:'جنسیت',male:'مرد',female:'زن',living:'زنده',deceased:'فوت شده',birthInfo:'تولد',deathInfo:'فوت',cancel:'انصراف',saveChanges:'ذخیره',loading:'در حال بارگذاری...',saving:'در حال ذخیره...',saved:'ذخیره شد'},en:{appTitle:'Family Tree',newTree:'New Tree',openFolder:'Folder',saveNow:'Save',addPerson:'Add Person',autoArrange:'Auto-Arrange',calcRelation:'Relationship',export:'Export',searchPlaceholder:'Search...',ready:'Ready',nodes:'persons',relationships:'relationships',editPerson:'Edit',uploadPhoto:'Upload Photo',removePhoto:'Remove Photo',firstName:'First Name',lastName:'Last Name',gender:'Gender',male:'Male',female:'Female',living:'Living',deceased:'Deceased',birthInfo:'Birth',deathInfo:'Death',cancel:'Cancel',saveChanges:'Save',loading:'Loading...',saving:'Saving...',saved:'Saved'}};}
    t(k){return this.translations[this.currentLang][k]||k;}
    setLanguage(l){this.currentLang=l;document.documentElement.lang=l;document.documentElement.dir=l==='fa'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=this.t(e.getAttribute('data-i18n')));}
}

// 3. FILE SYSTEM SYNC
class FileSystemSync{
    constructor(){this.isAvailable='showDirectoryPicker' in window;this.indexedDB=null;this.treesDirHandle=null;this.photosDirHandle=null;}
    async init(){if(this.isAvailable){try{await this.requestDir();}catch(e){await this.initIDB();}}else{await this.initIDB();}}
    async requestDir(){this.directoryHandle=await window.showDirectoryPicker({mode:'readwrite'});this.saveDirHandle=await this.directoryHandle.getDirectoryHandle('save',{create:true});this.treesDirHandle=await this.saveDirHandle.getDirectoryHandle('trees',{create:true});this.photosDirHandle=await this.saveDirHandle.getDirectoryHandle('photos',{create:true});}
    async initIDB(){return new Promise((res,rej)=>{const r=indexedDB.open('FamilyTreeDB',1);r.onerror=()=>rej(r.error);r.onsuccess=()=>{this.indexedDB=r.result;res();};r.onupgradeneeded=e=>{const db=e.target.result;if(!db.objectStoreNames.contains('trees'))db.createObjectStore('trees',{keyPath:'id'});if(!db.objectStoreNames.contains('photos'))db.createObjectStore('photos',{keyPath:'personId'});}});}
    async saveTree(id,data){if(this.treesDirHandle){const fh=await this.treesDirHandle.getFileHandle('tree_'+id+'.json',{create:true});const w=await fh.createWritable();await w.write(JSON.stringify(data,null,2));await w.close();}else if(this.indexedDB){const tx=this.indexedDB.transaction('trees','readwrite');tx.objectStore('trees').put({id:id,data:data});await tx.complete;}}
    async loadTree(id){if(this.treesDirHandle){try{const fh=await this.treesDirHandle.getFileHandle('tree_'+id+'.json');const f=await fh.getFile();return JSON.parse(await f.text());}catch(e){return null;}}else if(this.indexedDB){return new Promise(res=>{const tx=this.indexedDB.transaction('trees','readonly');const r=tx.objectStore('trees').get(id);r.onsuccess=()=>res(r.result?.data||null);r.onerror=()=>res(null);});}return null;}
    async savePhoto(pid,imgData){const fn='person_'+pid+'_avatar.webp';if(this.photosDirHandle){const fh=await this.photosDirHandle.getFileHandle(fn,{create:true});const w=await fh.createWritable();await w.write(imgData);await w.close();return 'save/photos/'+fn;}else if(this.indexedDB){const tx=this.indexedDB.transaction('photos','readwrite');tx.objectStore('photos').put({personId:pid,data:imgData,path:fn});await tx.complete;return fn;}return null;}
    async listTrees(){if(this.treesDirHandle){const fs=[];for await(const e of this.treesDirHandle.values()){if(e.kind==='file'&&e.name.endsWith('.json'))fs.push(e.name.replace('tree_','').replace('.json',''));}return fs;}else if(this.indexedDB){return new Promise(res=>{const tx=this.indexedDB.transaction('trees','readonly');const r=tx.objectStore('trees').getAllKeys();r.onsuccess=()=>res(r.result);r.onerror=()=>res([]);});}return [];}
    exportJSON(data){const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='family_tree.json';a.click();}
    compressImageToWebP(file,q=0.8){return new Promise(res=>{const c=document.createElement('canvas'),x=c.getContext('2d'),i=new Image();i.onload=()=>{let w=i.width,h=i.height;if(w>400||h>400){const r=Math.min(400/w,400/h);w*=r;h*=r;}c.width=w;c.height=h;x.drawImage(i,0,0,w,h);c.toBlob(b=>res(b),'image/webp',q);};i.src=URL.createObjectURL(file);});}
}

// 4. HISTORY MANAGER
class HistoryManager{
    constructor(max=50){this.undo=[];this.redo=[];this.max=max;this.recording=true;}
    push(cmd){if(!this.recording)return;this.undo.push(cmd);if(this.undo.length>this.max)this.undo.shift();this.redo=[];this.updateUI();}
    undo(){if(this.undo.length===0)return false;this.recording=false;const c=this.undo.pop();c.undo();this.redo.push(c);this.recording=true;this.updateUI();return true;}
    redo(){if(this.redo.length===0)return false;this.recording=false;const c=this.redo.pop();c.execute();this.undo.push(c);this.recording=true;this.updateUI();return true;}
    updateUI(){const ub=document.getElementById('btnUndo'),rb=document.getElementById('btnRedo'),uc=document.getElementById('undoCount'),rc=document.getElementById('redoCount');if(ub){ub.disabled=this.undo.length===0;if(uc)uc.textContent=this.undo.length;}if(rb){rb.disabled=this.redo.length===0;if(rc)rc.textContent=this.redo.length;}}
}

// 5. TREE GRAPH ENGINE
class TreeGraphEngine{
    constructor(){this.nodes=new Map();this.relationships=[];this.viewport={x:0,y:0,scale:1};this.dragging=false;this.lastPos={x:0,y:0};this.selected=null;this.highlighted=[];this.collapsed=new Set();this.nodeDim={w:200,h:120};this.canvasWrap=null;this.connLayer=null;this.nodesLayer=null;this.minimap=null;}
    init(){this.canvasWrap=document.getElementById('canvasWrapper');this.connLayer=document.getElementById('connectionsLayer');this.nodesLayer=document.getElementById('nodesLayer');this.minimap=document.getElementById('minimapCanvas');this.setupEvents();this.renderLoop();}
    setupEvents(){const c=document.getElementById('canvasContainer');c.addEventListener('mousedown',e=>{if(e.button===0&&!e.target.closest('.person-node')){this.dragging=true;this.lastPos={x:e.clientX,y:e.clientY};this.canvasWrap.style.cursor='grabbing';}});document.addEventListener('mousemove',e=>{if(this.dragging){this.viewport.x+=e.clientX-this.lastPos.x;this.viewport.y+=e.clientY-this.lastPos.y;this.lastPos={x:e.clientX,y:e.clientY};this.updateTransform();this.renderMinimap();}});document.addEventListener('mouseup',()=>{this.dragging=false;this.canvasWrap.style.cursor='grab';});c.addEventListener('wheel',e=>{e.preventDefault();this.zoom(e.deltaY>0?-0.05:0.05,e.clientX,e.clientY);},{passive:false});c.addEventListener('contextmenu',e=>{e.preventDefault();const n=e.target.closest('.person-node');if(n){this.selectNode(n.dataset.id);const cm=document.getElementById('contextMenu');cm.style.display='block';cm.style.left=e.clientX+'px';cm.style.top=e.clientY+'px';cm.classList.add('active');}});document.addEventListener('click',()=>{const cm=document.getElementById('contextMenu');if(cm){cm.classList.remove('active');setTimeout(()=>cm.style.display='none',150);}});document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='z'){e.preventDefault();e.shiftKey?app.historyManager.redo():app.historyManager.undo();}if(e.ctrlKey&&e.key==='y'){e.preventDefault();app.historyManager.redo();}if(e.ctrlKey&&e.key==='s'){e.preventDefault();app.autoSaveService.saveNow();}});document.getElementById('btnZoomIn')?.addEventListener('click',()=>this.zoom(0.1));document.getElementById('btnZoomOut')?.addEventListener('click',()=>this.zoom(-0.1));document.getElementById('btnZoomFit')?.addEventListener('click',()=>this.fitToScreen());}
    zoom(d,fx,fy){const os=this.viewport.scale,ns=Math.max(0.1,Math.min(3,os+d));if(fx&&fy){const wx=(fx-this.viewport.x)/os,wy=(fy-this.viewport.y)/os;this.viewport.x=fx-wx*ns;this.viewport.y=fy-wy*ns;}this.viewport.scale=ns;this.updateTransform();document.getElementById('zoomLevel').textContent=Math.round(ns*100)+'%';this.renderMinimap();}
    fitToScreen(){if(this.nodes.size===0)return;const b=this.getBounds(),ct=document.getElementById('canvasContainer'),sx=(ct.clientWidth-100)/(b.width||1),sy=(ct.clientHeight-100)/(b.height||1);this.viewport.scale=Math.min(sx,sy,1);this.viewport.x=(ct.clientWidth-b.width*this.viewport.scale)/2-b.x*this.viewport.scale;this.viewport.y=(ct.clientHeight-b.height*this.viewport.scale)/2-b.y*this.viewport.scale;this.updateTransform();this.renderMinimap();}
    updateTransform(){if(this.canvasWrap)this.canvasWrap.style.transform=`translate3d(${this.viewport.x}px,${this.viewport.y}px,0) scale(${this.viewport.scale})`;}
    addPerson(p){this.nodes.set(p.id,{...p,x:p.x||0,y:p.y||0});this.renderNode(p);this.updateStats();}
    updatePerson(p){if(this.nodes.has(p.id)){this.nodes.set(p.id,{...this.nodes.get(p.id),...p});this.renderNode(p);}}
    deletePerson(id){const p=this.nodes.get(id);if(!p)return;this.relationships=this.relationships.filter(r=>r.from!==id&&r.to!==id);this.nodes.delete(id);const el=document.querySelector('[data-id="'+id+'"]');if(el)el.remove();this.renderConnections();this.updateStats();}
    addRelationship(from,to,type='parent-child'){this.relationships.push({from,to,type});this.renderConnections();this.updateStats();}
    renderNode(p){let el=document.querySelector('[data-id="'+p.id+'"]');const col=this.collapsed.has(p.id);if(!el){el=document.createElement('div');el.className='person-node';el.dataset.id=p.id;el.style.left=p.x+'px';el.style.top=p.y+'px';el.innerHTML='<div class="node-header">'+(p.photo?'<img src="'+p.photo+'" class="node-photo">':'<div class="node-placeholder"><svg viewBox="0 0 24 24"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg></div>')+'<div class="node-actions"><button class="node-action-btn" onclick="app.uiController.editPerson(\''+p.id+'\')">✎</button></div>'+(col?'<span class="descendant-badge">+?</span>':'')+'</div><div class="node-body"><div class="node-name">'+(p.title||'')+' '+p.firstName+' '+p.lastName+'</div><div class="node-dates">'+(p.birthDateJalali?'🫸 '+p.birthDateJalali:'')+(p.deathDateJalali?' ✝ '+p.deathDateJalali:'')+'</div></div>'+(this.hasDescendants(p.id)?'<button class="collapse-toggle" onclick="event.stopPropagation();app.treeGraph.toggleBranch(\''+p.id+'\')">'+(col?'+':'−')+'</button>':'');el.addEventListener('click',e=>{e.stopPropagation();this.selectNode(p.id);});el.addEventListener('dblclick',e=>{e.stopPropagation();app.uiController.editPerson(p.id);});this.nodesLayer.appendChild(el);}else{el.style.left=p.x+'px';el.style.top=p.y+'px';el.querySelector('.node-name').textContent=(p.title||'')+' '+p.firstName+' '+p.lastName;if(p.photo){const pe=el.querySelector('.node-photo,.node-placeholder'),img=document.createElement('img');img.src=p.photo;img.className='node-photo';pe.parentNode.replaceChild(img,pe);}}}
    hasDescendants(id){return this.relationships.some(r=>r.from===id&&r.type==='parent-child');}
    toggleBranch(id){if(this.collapsed.has(id))this.collapsed.delete(id);else this.collapsed.add(id);this.renderConnections();this.renderAllNodes();}
    selectNode(id){const p=document.querySelector('.person-node.selected');if(p)p.classList.remove('selected');this.selected=id;const el=document.querySelector('[data-id="'+id+'"]');if(el)el.classList.add('selected');}
    highlightPath(path){document.querySelectorAll('.highlighted').forEach(e=>e.classList.remove('highlighted'));this.highlighted=path;path.forEach(id=>{const el=document.querySelector('[data-id="'+id+'"]');if(el)el.classList.add('highlighted');});this.renderConnections();}
    clearHighlights(){document.querySelectorAll('.highlighted').forEach(e=>e.classList.remove('highlighted'));this.highlighted=[];this.renderConnections();}
    renderConnections(){if(!this.connLayer)return;this.connLayer.innerHTML='';this.relationships.forEach(rel=>{const fn=this.nodes.get(rel.from),tn=this.nodes.get(rel.to);if(!fn||!tn||this.collapsed.has(rel.from))return;const hl=this.highlighted.includes(rel.from)&&this.highlighted.includes(rel.to);const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('class','connection-path'+(hl?' highlighted':''));const fx=fn.x+this.nodeDim.w/2,fy=fn.y+this.nodeDim.h,tx=tn.x+this.nodeDim.w/2,ty=tn.y,my=(fy+ty)/2;p.setAttribute('d','M '+fx+' '+fy+' C '+fx+' '+my+', '+tx+' '+my+', '+tx+' '+ty);this.connLayer.appendChild(p);});}
    renderAllNodes(){this.nodes.forEach(p=>this.renderNode(p));}
    getBounds(){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;this.nodes.forEach(p=>{minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x+this.nodeDim.w);maxY=Math.max(maxY,p.y+this.nodeDim.h);});return{x:minX===Infinity?0:minX,y:minY===Infinity?0:minY,width:maxX-minX,height:maxY-minY};}
    renderMinimap(){if(!this.minimap)return;const ctx=this.minimap.getContext('2d'),b=this.getBounds(),ct=document.getElementById('canvasContainer');ctx.clearRect(0,0,200,150);const sx=180/(b.width||1),sy=130/(b.height||1),sc=Math.min(sx,sy);ctx.fillStyle='#00A896';this.nodes.forEach(p=>ctx.fillRect((p.x-b.x)*sc+10,(p.y-b.y)*sc+10,4,3));const vp=document.getElementById('minimapViewport'),vpx=(-this.viewport.x/this.viewport.scale-b.x)*sc+10,vpy=(-this.viewport.y/this.viewport.scale-b.y)*sc+10;vp.style.left=vpx+'px';vp.style.top=vpy+'px';vp.style.width=(ct.clientWidth/this.viewport.scale)*sc+'px';vp.style.height=(ct.clientHeight/this.viewport.scale)*sc+'px';}
    renderLoop(){const loop=()=>{this.fps=Math.round(1000/(performance.now()-this.lastRenderTime));const el=document.getElementById('fpsCounter');if(el)el.textContent=this.fps+' FPS';this.lastRenderTime=performance.now();requestAnimationFrame(loop);};loop();}
    updateStats(){const nc=document.getElementById('nodeCount'),rc=document.getElementById('relationshipCount');if(nc)nc.innerHTML=this.nodes.size+' <span data-i18n="nodes">فرد</span>';if(rc)rc.innerHTML=this.relationships.length+' <span data-i18n="relationships">رابطه</span>';}
    autoLayout(){const gens=this.calcGens();let y=50;Object.keys(gens).sort((a,b)=>+a-+b).forEach(lvl=>{const mems=gens[lvl],tw=mems.length*(this.nodeDim.w+50);let x=-tw/2;mems.forEach(id=>{const p=this.nodes.get(id);if(p){p.x=x;p.y=y;this.renderNode(p);}x+=this.nodeDim.w+50;});y+=150;});this.renderConnections();this.fitToScreen();}
    calcGens(){const gens={},vis=new Set(),roots=[];this.nodes.forEach((p,id)=>{if(!this.relationships.some(r=>r.to===id&&r.type==='parent-child'))roots.push(id);});const q=roots.map(id=>({id,lvl:0}));while(q.length>0){const{id,lvl}=q.shift();if(vis.has(id))continue;vis.add(id);if(!gens[lvl])gens[lvl]=[];gens[lvl].push(id);this.relationships.filter(r=>r.from===id&&r.type==='parent-child').forEach(r=>{if(!vis.has(r.to))q.push({id:r.to,lvl:lvl+1});});}return gens;}
    serialize(){return{nodes:Array.from(this.nodes.entries()),relationships:[...this.relationships],viewport:{...this.viewport},collapsed:Array.from(this.collapsed)};}
    deserialize(d){this.nodes.clear();d.nodes.forEach(([id,p])=>this.nodes.set(id,p));this.relationships=d.relationships||[];this.viewport=d.viewport||{x:0,y:0,scale:1};this.collapsed=new Set(d.collapsed||[]);this.renderAllNodes();this.renderConnections();this.updateTransform();this.updateStats();}
}

// 6. KINSHIP CALCULATOR
class KinshipCalculator{
    constructor(tree,i18n){this.tree=tree;this.i18n=i18n;}
    findPath(aId,bId){if(aId===bId)return[aId];const g=this.buildGraph();const fq=[[aId]],fv=new Set([aId]),bq=[[bId]],bv=new Set([bId]);for(let i=0;i<1000&&fq.length>0&&bq.length>0;i++){const fp=fq.shift(),fc=fp[fp.length-1];for(const n of(g.get(fc)||[])){if(bv.has(n)){const bp=bq.find(p=>p[p.length-1]===n)||[n];return[...fp,...bp.slice(1).reverse()];}if(!fv.has(n)){fv.add(n);fq.push([...fp,n]);}}const bp=bq.shift(),bc=bp[bp.length-1];for(const n of(g.get(bc)||[])){if(fv.has(n)){const fp=fq.find(p=>p[p.length-1]===n)||[n];return[...fp,...bp.slice(1).reverse()];}if(!bv.has(n)){bv.add(n);bq.push([...bp,n]);}}}return null;}
    buildGraph(){const g=new Map();const ae=(a,b)=>{if(!g.has(a))g.set(a,[]);if(!g.has(b))g.set(b,[]);if(!g.get(a).includes(b))g.get(a).push(b);if(!g.get(b).includes(a))g.get(b).push(a);};this.tree.relationships.forEach(r=>ae(r.from,r.to));return g;}
    describe(path){if(!path||path.length<2)return null;const nodes=path.map(id=>this.tree.nodes.get(id)).filter(Boolean);if(nodes.length<2)return null;const len=nodes.length;if(len===2){const a=nodes[0],b=nodes[1];if(this.tree.relationships.some(r=>r.from===a.id&&r.to===b.id&&r.type==='parent-child'))return{fa:a.gender==='male'?'پدر':'مادر',en:a.gender==='male'?'Father':'Mother'};if(this.tree.relationships.some(r=>r.from===b.id&&r.to===a.id&&r.type==='parent-child'))return{fa:a.gender==='male'?'پسر':'دختر',en:a.gender==='male'?'Son':'Daughter'};return{fa:'خویشاوند',en:'Relative'};}if(len===3)return{fa:'پدربزرگ/مادربزرگ یا نوه',en:'Grandparent/Grandchild'};if(len===4)return{fa:'عمو/دایی/عمه/خاله',en:'Uncle/Aunt'};return{fa:'خویشاوند دور',en:'Distant Relative'};}
}

// 7. AUTO-SAVE SERVICE
class AutoSaveService{
    constructor(fs,tree,interval=10000){this.fs=fs;this.tree=tree;this.interval=interval;this.timer=null;this.dirty=false;this.treeId='default';this.lastSaved=null;}
    start(){this.timer=setInterval(()=>{if(this.dirty)this.saveNow();},this.interval);}
    markDirty(){this.dirty=true;this.updateStatus('saving');}
    async saveNow(){if(!this.dirty)return;this.updateStatus('saving');try{await this.fs.saveTree(this.treeId,this.tree.serialize());this.dirty=false;this.lastSaved=new Date();this.updateStatus('saved');}catch(e){console.error(e);this.updateStatus('error');}}
    updateStatus(s){const ss=document.getElementById('saveStatus'),ls=document.getElementById('lastSaved'),dot=ss?.querySelector('.status-dot'),txt=ss?.querySelector('span:last-child');if(!ss)return;if(s==='saving'){dot?.classList.add('saving');if(app?.i18nManager)txt.textContent=app.i18nManager.t('saving');}else if(s==='saved'){dot?.classList.remove('saving');if(app?.i18nManager)txt.textContent=app.i18nManager.t('saved');if(ls&&this.lastSaved)ls.textContent='('+this.lastSaved.toLocaleTimeString()+')';}}
    setTreeId(id){this.treeId=id;}
}

// 8. UI CONTROLLER
class UIController{
    constructor(){this.personModal=document.getElementById('personModal');this.relationModal=document.getElementById('relationModal');this.exportModal=document.getElementById('exportModal');this.searchInput=document.getElementById('searchInput');this.searchResults=document.getElementById('searchResults');}
    init(){this.setupModals();this.setupToolbar();this.setupSearch();this.setupContext();}
    setupModals(){document.getElementById('closePersonModal')?.addEventListener('click',()=>this.closePersonModal());document.getElementById('cancelPersonEdit')?.addEventListener('click',()=>this.closePersonModal());document.getElementById('savePerson')?.addEventListener('click',()=>this.savePerson());document.getElementById('btnUploadPhoto')?.addEventListener('click',()=>document.getElementById('photoInput').click());document.getElementById('btnRemovePhoto')?.addEventListener('click',()=>this.removePhoto());document.getElementById('photoInput')?.addEventListener('change',e=>this.handlePhoto(e));document.getElementById('closeRelationModal')?.addEventListener('click',()=>this.closeRelationModal());document.getElementById('btnCalculatePath')?.addEventListener('click',()=>this.calcRelation());document.getElementById('closeExportModal')?.addEventListener('click',()=>this.closeExportModal());document.getElementById('exportJSON')?.addEventListener('click',()=>{app.fileSystem.exportJSON(app.treeGraph.serialize());this.closeExportModal();});document.getElementById('exportSVG')?.addEventListener('click',()=>{const b=new Blob([document.getElementById('connectionsLayer').outerHTML],{type:'image/svg+xml'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='tree.svg';a.click();this.closeExportModal();});document.getElementById('exportPrint')?.addEventListener('click',()=>window.print());}
    setupToolbar(){document.getElementById('btnAddPerson')?.addEventListener('click',()=>this.addPerson());document.getElementById('btnAutoArrange')?.addEventListener('click',()=>app.treeGraph.autoLayout());document.getElementById('btnCalculateRelation')?.addEventListener('click',()=>this.openRelationModal());document.getElementById('btnExport')?.addEventListener('click',()=>this.openExportModal());document.getElementById('btnToggleLang')?.addEventListener('click',()=>app.i18nManager.setLanguage(app.i18nManager.currentLang==='fa'?'en':'fa'));document.getElementById('btnSaveNow')?.addEventListener('click',()=>app.autoSaveService.saveNow());document.getElementById('btnOpenDirectory')?.addEventListener('click',async()=>{await app.fileSystem.init();await this.loadTreeList();});document.getElementById('btnNewTree')?.addEventListener('click',()=>{const n=prompt('Tree name:');if(n){const o=document.createElement('option');o.value=n.toLowerCase().replace(/\s+/g,'_');o.textContent=n;document.getElementById('treeSelector').appendChild(o);}});}
    setupSearch(){if(this.searchInput){this.searchInput.addEventListener('input',e=>this.search(e.target.value));this.searchInput.addEventListener('focus',()=>{if(this.searchResults.children.length>0)this.searchResults.classList.add('active');});}document.addEventListener('click',e=>{if(!e.target.closest('.search-container'))this.searchResults?.classList.remove('active');});}
    setupContext(){document.getElementById('contextMenu')?.querySelectorAll('.context-item').forEach(item=>{item.addEventListener('click',()=>{const a=item.dataset.action,id=app.treeGraph.selected;if(!id)return;if(a==='editPerson')this.editPerson(id);else if(a==='deletePerson'){if(confirm('Delete?'))app.historyManager.push({execute:()=>app.treeGraph.deletePerson(id),undo:()=>{}});app.treeGraph.hideContextMenu();}});});}
    editPerson(id){const p=app.treeGraph.nodes.get(id);if(!p)return;document.getElementById('personId').value=p.id;document.getElementById('firstName').value=p.firstName||'';document.getElementById('lastName').value=p.lastName||'';document.getElementById('title').value=p.title||'';document.querySelector('input[name="gender"][value="'+(p.gender||'male')+'"]').checked=true;document.querySelector('input[name="livingStatus"][value="'+(p.livingStatus||'living')+'"]').checked=true;document.getElementById('birthDateJalali').value=p.birthDateJalali||'';document.getElementById('birthDateGregorian').value=p.birthDateGregorian||'';document.getElementById('birthPlace').value=p.birthPlace||'';const pp=document.getElementById('photoPreview');pp.innerHTML=p.photo?'<img src="'+p.photo+'" style="width:100%;height:100%;object-fit:cover;border-radius:50%;">':pp.innerHTML;this.personModal.classList.add('active');}
    closePersonModal(){this.personModal.classList.remove('active');}
    savePerson(){const id=document.getElementById('personId').value||'p_'+Date.now()+'_'+Math.random().toString(36).substr(2,9),isNew=!app.treeGraph.nodes.has(id),p={id:id,firstName:document.getElementById('firstName').value,lastName:document.getElementById('lastName').value,title:document.getElementById('title').value,gender:document.querySelector('input[name="gender"]:checked').value,livingStatus:document.querySelector('input[name="livingStatus"]:checked').value,birthDateJalali:document.getElementById('birthDateJalali').value,birthDateGregorian:document.getElementById('birthDateGregorian').value,birthPlace:document.getElementById('birthPlace').value,x:isNew?0:app.treeGraph.nodes.get(id)?.x,y:isNew?0:app.treeGraph.nodes.get(id)?.y};const ep=app.treeGraph.nodes.get(id);if(ep&&ep.photo&&!p.photo)p.photo=ep.photo;if(isNew)app.historyManager.push({execute:()=>app.treeGraph.addPerson(p),undo:()=>app.treeGraph.deletePerson(id)});else app.historyManager.push({execute:()=>app.treeGraph.updatePerson(p),undo:()=>app.treeGraph.updatePerson(ep)});app.autoSaveService.markDirty();this.closePersonModal();}
    async handlePhoto(e){const f=e.target.files[0],id=document.getElementById('personId').value;if(!f||!id)return;const wb=await app.fileSystem.compressImageToWebP(f),ab=await wb.arrayBuffer(),pp=await app.fileSystem.savePhoto(id,ab),p=app.treeGraph.nodes.get(id);if(p){p.photo=pp||URL.createObjectURL(wb);app.treeGraph.renderNode(p);}document.getElementById('photoPreview').innerHTML='<img src="'+URL.createObjectURL(wb)+'" style="width:100%;height:100%;object-fit:cover;border-radius:50%;">';}
    removePhoto(){const id=document.getElementById('personId').value;if(!id)return;const p=app.treeGraph.nodes.get(id);if(p){delete p.photo;app.treeGraph.renderNode(p);}document.getElementById('photoPreview').innerHTML='<svg viewBox="0 0 100 100" width="120" height="120"><circle cx="50" cy="50" r="48" fill="#F5EFEB" stroke="#D4AF37" stroke-width="2"/><circle cx="50" cy="40" r="18" fill="#D1C7BD"/><path d="M25 85c0-14 11-25 25-25s25 11 25 25" fill="#D1C7BD"/></svg>';}
    addPerson(){document.getElementById('personForm').reset();document.getElementById('personId').value='';document.getElementById('photoPreview').innerHTML='<svg viewBox="0 0 100 100" width="120" height="120"><circle cx="50" cy="50" r="48" fill="#F5EFEB" stroke="#D4AF37" stroke-width="2"/><circle cx="50" cy="40" r="18" fill="#D1C7BD"/><path d="M25 85c0-14 11-25 25-25s25 11 25 25" fill="#D1C7BD"/></svg>';this.personModal.classList.add('active');}
    openRelationModal(){const sa=document.getElementById('personASelect'),sb=document.getElementById('personBSelect');sa.innerHTML='';sb.innerHTML='';app.treeGraph.nodes.forEach((p,id)=>{const o=document.createElement('option');o.value=id;o.textContent=p.firstName+' '+p.lastName;sa.appendChild(o.cloneNode(true));sb.appendChild(o);});this.relationModal.classList.add('active');}
    closeRelationModal(){this.relationModal.classList.remove('active');app.treeGraph.clearHighlights();}
    calcRelation(){const a=document.getElementById('personASelect').value,b=document.getElementById('personBSelect').value;if(!a||!b)return;const path=app.kinshipCalc.findPath(a,b);if(path){app.treeGraph.highlightPath(path);const d=app.kinshipCalc.describe(path);document.getElementById('relationResult').innerHTML='<div class="relation-path">'+(path.length-1)+' steps</div><div class="relation-description">'+(app.i18nManager.currentLang==='fa'?d.fa:d.en)+'</div>';}else document.getElementById('relationResult').innerHTML='<div class="result-placeholder">No relationship found</div>';}
    openExportModal(){this.exportModal.classList.add('active');}
    closeExportModal(){this.exportModal.classList.remove('active');}
    async search(q){if(!q||q.length<2){this.searchResults.classList.remove('active');this.searchResults.innerHTML='';return;}const res=[];app.treeGraph.nodes.forEach((p,id)=>{if((p.firstName+' '+p.lastName).toLowerCase().includes(q.toLowerCase()))res.push({id,p});});this.searchResults.innerHTML='';res.slice(0,10).forEach(({id,p})=>{const d=document.createElement('div');d.className='search-result-item';d.innerHTML='<strong>'+p.firstName+' '+p.lastName+'</strong>';d.addEventListener('click',()=>{app.treeGraph.selectNode(id);this.searchResults.classList.remove('active');this.searchInput.value='';});this.searchResults.appendChild(d);});if(res.length>0)this.searchResults.classList.add('active');}
    async loadTreeList(){const ids=await app.fileSystem.listTrees(),sel=document.getElementById('treeSelector');sel.innerHTML='';ids.forEach(id=>{const o=document.createElement('option');o.value=id;o.textContent=id;sel.appendChild(o);});if(ids.length===0){const o=document.createElement('option');o.value='default';o.textContent=app.i18nManager.currentLang==='fa'?'شجره پیش‌فرض':'Default Tree';sel.appendChild(o);}}
}

// MAIN APP
class FamilyTreeApp{
    constructor(){this.jalali=new JalaliEngine();this.i18n=new I18nManager();this.fileSystem=new FileSystemSync();this.history=new HistoryManager();this.treeGraph=new TreeGraphEngine();this.kinshipCalc=null;this.autoSaveService=null;this.uiController=new UIController();}
    async init(){try{document.getElementById('loadingOverlay')?.classList.add('active');await this.fileSystem.init();this.treeGraph.init();this.uiController.init();this.kinshipCalc=new KinshipCalculator(this.treeGraph,this.i18n);this.autoSaveService=new AutoSaveService(this.fileSystem,this.treeGraph);this.autoSaveService.start();await this.loadTree();this.setupDateListeners();setTimeout(()=>document.getElementById('loadingOverlay')?.classList.remove('active'),500);console.log('Family Tree Builder initialized');}catch(e){console.error(e);document.getElementById('loadingOverlay')?.classList.remove('active');}}
    async loadTree(){const ids=await this.fileSystem.listTrees();if(ids.length>0){const d=await this.fileSystem.loadTree(ids[0]);if(d){this.treeGraph.deserialize(d);this.autoSaveService.setTreeId(ids[0]);}}else{this.createSample();}await this.uiController.loadTreeList();}
    createSample(){const l=app.i18nManager.currentLang==='fa';const persons=[{id:'p1',firstName:l?'احمد':'Ahmad',lastName:l?'محمدی':'Mohammadi',gender:'male',birthDateJalali:'1320/05/15',x:-100,y:50},{id:'p2',firstName:l?'مریم':'Maryam',lastName:l?'محمدی':'Mohammadi',gender:'female',birthDateJalali:'1325/08/20',x:100,y:50},{id:'p3',firstName:l?'حسن':'Hassan',lastName:l?'محمدی':'Mohammadi',gender:'male',birthDateJalali:'1350/03/10',x:-100,y:200},{id:'p4',firstName:l?'فاطمه':'Fateme',lastName:l?'حسینی':'Hosseini',gender:'female',birthDateJalali:'1355/07/25',x:100,y:200},{id:'p5',firstName:l?'علی':'Ali',lastName:l?'محمدی':'Mohammadi',gender:'male',birthDateJalali:'1380/01/01',x:0,y:350}];persons.forEach(p=>this.treeGraph.addPerson(p));this.treeGraph.addRelationship('p1','p3','parent-child');this.treeGraph.addRelationship('p2','p3','parent-child');this.treeGraph.addRelationship('p3','p5','parent-child');this.treeGraph.addRelationship('p4','p5','parent-child');this.autoSaveService.markDirty();}
    setupDateListeners(){['birth','death'].forEach(type=>{const ji=document.getElementById(type+'DateJalali'),gi=document.getElementById(type+'DateGregorian');if(ji)ji.addEventListener('blur',()=>{const p=this.jalali.parseDate(ji.value);if(p){const g=this.jalali.jalaliToGregorian(p[0],p[1],p[2]);if(gi)gi.value=this.jalali.formatDate(g.year,g.month,g.day);}});if(gi)gi.addEventListener('blur',()=>{const p=this.jalali.parseDate(gi.value);if(p){const j=this.jalali.gregorianToJalali(p[0],p[1],p[2]);if(ji)ji.value=this.jalali.formatDate(j.year,j.month,j.day);}});});}
}

let app;
document.addEventListener('DOMContentLoaded',()=>{app=new FamilyTreeApp();app.init();});
window.app=app;
